/* Lecture wording copied from the TRN4211 notes. UI labels only sit in zh. */
var TERMS = [
  { id: "frame", group: "Watertight door", en: "Frame", zh: "門框",
    def: "",
    note: "（第 15 頁水密門圖上標示，正文無定義）水密門周圍的框架。",
    source: "00_術語表_中英定義.md · 艙口與水密門" },
  { id: "hinge", group: "Watertight door", en: "Hinge", zh: "鉸",
    def: "",
    note: "（第 15 頁水密門圖上標示，正文無定義）門扇藉以轉動的鉸鏈。",
    source: "00_術語表_中英定義.md · 艙口與水密門" },
  { id: "wedge", group: "Watertight door", en: "Wedge", zh: "楔",
    def: "",
    note: "（第 15 頁水密門圖上標示，正文無定義）門緣的楔形部分，關閉時壓入門框。",
    model: "繪於門扇關閉緣，剖面為楔形，以便辨認。",
    source: "00_術語表_中英定義.md · 艙口與水密門" },
  { id: "dog", group: "Watertight door", en: "Dog", zh: "扣件",
    def: "A small metal fastener or clip used to secure doors, hatch covers, etc.",
    note: "用以扣緊門及艙蓋的小型金屬扣件。",
    model: "水密門周邊與艙蓋邊緣均有繪出。點選後兩處一併標示。",
    source: "00_術語表_中英定義.md · 艙口與水密門" },
  { id: "escape-manhole", group: "Watertight door", en: "Escape manhole", zh: "逃生人孔",
    def: "",
    note: "（第 14 頁圖上標示，正文無定義）圖註為 clips operated from both sides of manhole。大門上的小門，兩側均可操作夾扣。",
    model: "小蓋略為打開。門扇外側與內側各有一枚夾扣。",
    source: "00_術語表_中英定義.md · 艙口與水密門" },

  { id: "coaming", group: "Hatchway", en: "Coaming", zh: "艙口圍板",
    def: "The vertical plates built around a hatchway. The fore and aft pieces are called coamings.",
    note: "艙口四周的垂直板。前後兩塊稱為 coaming。",
    model: "此頁只放大艙口一角，故前後向只繪出一塊。",
    source: "00_術語表_中英定義.md · 艙口與水密門" },
  { id: "head-ledge", group: "Hatchway", en: "Head ledge", zh: "艙口端樑",
    def: "Those athwartship are called head ledges. The head ledges rest on the beams and the carlings extending between the beams.",
    note: "橫向的兩塊。端樑坐於樑及樑與樑之間的短樑上。與 coaming 宜一併記憶。",
    model: "此頁只放大艙口一角，故橫向只繪出一塊，並可見其坐於樑上。",
    source: "00_術語表_中英定義.md · 艙口與水密門" },
  { id: "beam", group: "Hatchway", en: "Beam", zh: "樑",
    def: "The head ledges rest on the beams and the carlings extending between the beams.",
    note: "橫向構件。艙口端樑坐於其上。講義沒有單獨的定義句，上句出自 Head ledge。",
    model: "繪於端樑下方，橫跨艙口。",
    source: "00_術語表_中英定義.md · 艙口與水密門" },
  { id: "carling", group: "Hatchway", en: "Carling", zh: "短樑",
    def: "The head ledges rest on the beams and the carlings extending between the beams.",
    note: "連接各樑之間的構件。講義沒有單獨的定義句，上句出自 Head ledge。",
    model: "繪於兩條樑之間。",
    source: "00_術語表_中英定義.md · 艙口與水密門" },
  { id: "wing-nut", group: "Hatchway", en: "Wing nut", zh: "蝶形螺母",
    def: "It can be clamped down by means of wing nuts. The wing nuts should be crewed home hand-tight.",
    note: "用以扣實艙蓋，用手扭緊即可，無需工具。講義原文 crewed 為印刷錯誤，應為 screwed。考試仍照講義原文作答。",
    source: "00_術語表_中英定義.md · 艙口與水密門" },
  { id: "double-clip", group: "Hatchway", en: "Double clip", zh: "雙面扣",
    def: "Some hatch covers are fitted with double clips to enable them to be opened from either side.",
    note: "部分艙蓋裝有雙面扣，以便從任一側開啟。人若被困在內，亦可自行開門。",
    model: "繪成貫通艙蓋邊緣的扣件，上、下各有一個手柄。",
    source: "00_術語表_中英定義.md · 艙口與水密門" }
];
