/* Lecture wording copied from the TRN4211 notes. UI labels only sit in zh. */
var TERMS = [
  { id: "port", group: "Directions", en: "Port", zh: "左舷", directions: true,
    def: "The Port side is on the left of a ship.",
    note: "面向船首的左側。夜間顯示紅燈，編號用雙數。",
    source: "00_術語表_中英定義.md · 方向與位置" },
  { id: "starboard", group: "Directions", en: "Starboard", zh: "右舷", directions: true,
    def: "When facing the bow, the Starboard side is on the right hand.",
    note: "面向船首的右側。夜間顯示綠燈，編號用單數。",
    source: "00_術語表_中英定義.md · 方向與位置" },
  { id: "bow", group: "Directions", en: "Bow", zh: "船艏",
    def: "The front part or forward end of a ship, immediately abaft the stem. The curved surface (the sides \"Port and Starboard\" of a hull from deck to keel) of the fore part is called the bow (Port or Starboard).",
    note: "緊接艏柱之後的一段彎曲船身，分為 port bow 與 starboard bow。",
    source: "00_術語表_中英定義.md · 方向與位置" },
  { id: "quarter", group: "Directions", en: "Quarter", zh: "船艉側",
    def: "The curved surface of the after part is called the quarter (Port or Starboard).",
    note: "船尾一段彎曲船身，分為 port quarter 與 starboard quarter。",
    source: "00_術語表_中英定義.md · 方向與位置" },
  { id: "forward", group: "Directions", en: "Forward", zh: "向前", directions: true,
    def: "Forward – in the direction of, at, or near the stem. Aft – in the direction of, at, or near the stern.",
    note: "朝向艏柱為 forward，朝向船尾為 aft。",
    source: "00_術語表_中英定義.md · 方向與位置" },
  { id: "aft", group: "Directions", en: "Aft", zh: "向後", directions: true,
    def: "Forward – in the direction of, at, or near the stem. Aft – in the direction of, at, or near the stern.",
    note: "朝向艏柱為 forward，朝向船尾為 aft。",
    source: "00_術語表_中英定義.md · 方向與位置" },
  { id: "ahead", group: "Directions", en: "Ahead", zh: "正前", directions: true,
    def: "Ahead, astern, abeam are the relative bearings.",
    note: "三個基準：正前、正後、正橫。",
    source: "00_術語表_中英定義.md · 方位、報告與通訊用語" },
  { id: "abeam", group: "Directions", en: "Abeam", zh: "正橫", directions: true,
    def: "Ahead, astern, abeam are the relative bearings.",
    note: "三個基準：正前、正後、正橫。",
    source: "00_術語表_中英定義.md · 方位、報告與通訊用語" },
  { id: "astern", group: "Directions", en: "Astern", zh: "正後", directions: true,
    def: "Ahead, astern, abeam are the relative bearings.",
    note: "三個基準：正前、正後、正橫。",
    source: "00_術語表_中英定義.md · 方位、報告與通訊用語" },
  { id: "on-the-bow", group: "Directions", en: "On the bow", zh: "艏舷側", directions: true,
    def: "When an object is midway between ahead and abeam it is said to bear on the bow.",
    note: "位於 ahead 與 abeam 之間。",
    source: "00_術語表_中英定義.md · 方位、報告與通訊用語" },
  { id: "on-the-quarter", group: "Directions", en: "On the quarter", zh: "艉舷側", directions: true,
    def: "When midway between abeam and astern it is said to bear on the quarter.",
    note: "位於 abeam 與 astern 之間。",
    source: "00_術語表_中英定義.md · 方位、報告與通訊用語" },
  { id: "amidships", group: "Directions", en: "Amidships", zh: "船舯", directions: true,
    def: "It describes the position roughly in the middle of the ship, and it also describes any position on the fore and aft line.\n\nThe point midway between the forward and after perpendiculars.",
    note: "有兩個意思：約在船舶中部；亦可指前後中線上的任何一點。後者為精確定義，與「約在船中」的日常用法不同。",
    source: "00_術語表_中英定義.md · 方向與位置；其餘主尺度" },

  { id: "hull", group: "Hull", en: "Hull", zh: "船體",
    def: "The hull is divided into three parts.",
    note: "Hull 即船的水密主體，指由船底至上甲板的全部外板。Hull 之上才是上層建築（設有甲板的圍蔽或開敞結構）及甲板室（位於乾舷甲板或以上、不屬上層建築者）。此分界其後計算乾舷、噸位及載重線時均須使用。",
    source: "00_術語表_中英定義.md · 船體結構；00_溫習清單.md · Hull" },
  { id: "stem", group: "Hull", en: "Stem", zh: "艏柱",
    def: "Fore Part – it ends in the stem.",
    note: "船體最前端的結構柱。",
    source: "00_術語表_中英定義.md · 方向與位置" },
  { id: "stern", group: "Hull", en: "Stern", zh: "船尾",
    def: "The after end of a ship. It ends in the stern.",
    note: "船體的最後端。",
    source: "00_術語表_中英定義.md · 方向與位置" },
  { id: "forefoot", group: "Hull", en: "Forefoot", zh: "艏踵",
    def: "",
    note: "（第 4 頁圖上標示，正文無定義）艏柱與龍骨交接的彎位。",
    source: "00_術語表_中英定義.md · 船體結構" },
  { id: "keel", group: "Hull", en: "Keel", zh: "龍骨",
    def: "The keel is the backbone of the ship. Timber or other material running the length of a ship to provide longitudinal strength.",
    note: "船的「脊骨」，提供縱向強度。",
    model: "繪成略為突出船底，以便點選。",
    source: "00_術語表_中英定義.md · 船體結構" },
  { id: "bilge-keel", group: "Hull", en: "Bilge keel", zh: "舭龍骨",
    def: "A long fin secured to the hull at the turn of the bilge, designed to decrease the rolling of a ship.",
    note: "裝於船底轉角的長鰭片，用以減少橫搖。與龍骨不同：龍骨提供縱向強度，舭龍骨用以減搖。",
    source: "00_術語表_中英定義.md · 船體結構" },
  { id: "flare", group: "Hull", en: "Flare", zh: "外飄",
    def: "When the ship's sides curve outwards above the waterline they are said to be flared.",
    note: "水線以上船側向外彎曲，多見於船艏。",
    source: "00_術語表_中英定義.md · 船體結構" },
  { id: "tumble-home", group: "Hull", en: "Tumble home", zh: "內傾",
    def: "When the ship's sides curve inwards above the waterline they are said to tumble home.",
    note: "水線以上船側向內彎曲。現代船舶多為直壁（wall-sided），外飄與內傾皆無。",
    model: "本模型船舯為直壁，沒有 tumble home。船艏水線以上才略有外飄。",
    source: "00_術語表_中英定義.md · 船體結構" },
  { id: "camber", group: "Hull", en: "Camber (round of beam)", zh: "梁拱",
    def: "The curved given to the surface of exposed decks to accelerate runoff, so that water will drain away to the ship's side, know as \"round of beam\".",
    note: "甲板的橫向弧形，使水排向兩舷。此為排水設計。",
    source: "00_術語表_中英定義.md · 船體結構" },
  { id: "sheer", group: "Hull", en: "Sheer", zh: "舷弧",
    def: "Longitudinal deck curvature. The upward sweep from amidships to forward & aft of the upper deck.",
    note: "甲板的縱向弧度。與梁拱讀來相近，方向相差 90°。",
    source: "00_術語表_中英定義.md · 船體結構" },

  { id: "forecastle", group: "Decks", en: "Forecastle", zh: "艏樓",
    def: "The ends of the upper deck if built up in tiers of decks are called forecastle and after castle.",
    note: "上甲板兩端加高的部分。",
    source: "00_術語表_中英定義.md · 船體結構" },
  { id: "poop", group: "Decks", en: "After castle / poop", zh: "艉樓",
    def: "The ends of the upper deck if built up in tiers of decks are called forecastle and after castle.",
    note: "上甲板兩端加高的部分。",
    source: "00_術語表_中英定義.md · 船體結構" },
  { id: "waist", group: "Decks", en: "Waist", zh: "舯部凹段",
    def: "The lower part between the castles is called waist.",
    note: "兩個 castle 之間凹下的一段（圖上亦稱 well deck）。",
    source: "00_術語表_中英定義.md · 船體結構" },
  { id: "main-deck", group: "Decks", en: "Main deck / upper deck", zh: "主甲板",
    def: "Main deck is the highest (uppermost continuous) deck of the hull, also called the upper deck, usually but not always the weather deck.",
    note: "船體最上一層連續甲板。其上全部屬上層建築。",
    source: "00_術語表_中英定義.md · 船體結構" },
  { id: "weather-deck", group: "Decks", en: "Weather deck", zh: "露天甲板",
    def: "The deck in a ship exposed to the outside.",
    note: "暴露於船外的一層甲板。",
    model: "本船的主甲板即為露天的一層，故點選同一塊甲板。講義寫 usually but not always the weather deck。",
    source: "00_術語表_中英定義.md · 船體結構" },
  { id: "superstructure", group: "Decks", en: "Superstructure", zh: "上層建築",
    def: "Anything above the main deck is superstructure.",
    note: "主甲板以上的結構。",
    source: "00_術語表_中英定義.md · 船體結構" },
  { id: "bridge", group: "Decks", en: "Bridge deck", zh: "橋樓甲板",
    def: "Boat deck where lifeboats are stored; bridge deck where the wheelhouse is located; flight deck from which aircraft take off or land.",
    note: "按用途命名的甲板。",
    source: "00_術語表_中英定義.md · 船體結構" },
  { id: "boat-deck", group: "Decks", en: "Boat deck", zh: "艇甲板",
    def: "Boat deck where lifeboats are stored; bridge deck where the wheelhouse is located; flight deck from which aircraft take off or land.",
    note: "按用途命名的甲板。",
    source: "00_術語表_中英定義.md · 船體結構" },
  { id: "bulwark", group: "Decks", en: "Bulwark", zh: "舷牆",
    def: "Barrier of stiffened plating at the outboard edge of the main or upper deck to prevent or inhibit entry of the sea. They are fitted for the safety of the crew, to be at least 1m high, supported by stays from the deck.",
    note: "甲板邊緣的擋水板牆，高度至少 1 米，用以阻擋海水，並防止人員及貨物落海。",
    source: "00_術語表_中英定義.md · 船體結構" },
  { id: "freeing-port", group: "Decks", en: "Freeing port", zh: "排水孔",
    def: "An opening in the bottom of a bulwark, for rapid drainage of a weather deck in heavy seas.",
    note: "舷牆底部的開口，供大浪時迅速排走甲板上的水。",
    source: "00_術語表_中英定義.md · 船體結構" },
  { id: "gangway", group: "Decks", en: "Gangway", zh: "舷梯／通道",
    def: "A sloped platform between ship and shore, or a passageway in a ship or the opening in the bulwarks, by which the ship is entered / left.",
    note: "法定要求：註冊長度 30 米或以上的船舶須備有（第 369AH 章）。",
    model: "碼頭沒有繪出。這條斜板即講義所稱的 sloped platform。",
    source: "00_術語表_中英定義.md · 船體結構" },
  { id: "accommodation-ladder", group: "Decks", en: "Accommodation ladder", zh: "舷梯",
    def: "",
    note: "法定要求：註冊長度 120 米或以上的船舶須備有（第 369AH 章）。與 gangway 的長度標準不同，容易混淆。",
    source: "00_術語表_中英定義.md · 船體結構" },
  { id: "mast", group: "Decks", en: "Mast", zh: "桅",
    def: "The Mast is forward, while the funnel is aft when defining an object.",
    note: "講義的前後定位習慣：桅在前，煙囪在後。",
    source: "00_術語表_中英定義.md · 方向與位置" },
  { id: "funnel", group: "Decks", en: "Funnel", zh: "煙囪",
    def: "The Mast is forward, while the funnel is aft when defining an object.",
    note: "講義的前後定位習慣：桅在前，煙囪在後。",
    source: "00_術語表_中英定義.md · 方向與位置" },
  { id: "jack-staff", group: "Decks", en: "Jack staff", zh: "艏旗桿",
    def: "The ensign staff is right aft and the jack staff right forward.",
    note: "一在最後，一在最前。",
    source: "00_術語表_中英定義.md · 方向與位置" },
  { id: "ensign-staff", group: "Decks", en: "Ensign staff", zh: "艉旗桿",
    def: "The ensign staff is right aft and the jack staff right forward.",
    note: "一在最後，一在最前。",
    source: "00_術語表_中英定義.md · 方向與位置" },

  { id: "hatch", group: "Cargo", en: "Hatch", zh: "艙口",
    def: "An opening in the deck is called a hatch. It allows access to the compartments below, and a lid called a hatch cover is hinged to it.",
    note: "甲板上的開口，其上設有艙蓋。",
    source: "00_術語表_中英定義.md · 艙口與水密門" },
  { id: "hatch-cover", group: "Cargo", en: "Hatch cover", zh: "艙蓋",
    def: "An opening in the deck is called a hatch. It allows access to the compartments below, and a lid called a hatch cover is hinged to it.",
    note: "甲板上的開口，其上設有艙蓋。雜貨船的特徵包括艙口加裝水密艙蓋。",
    source: "00_術語表_中英定義.md · 艙口與水密門；00_溫習清單.md · general cargo ship 特徵" },
  { id: "coaming", group: "Cargo", en: "Coaming", zh: "艙口圍板",
    def: "The vertical plates built around a hatchway. The fore and aft pieces are called coamings.",
    note: "前後兩件，為垂直板。",
    source: "00_術語表_中英定義.md · 艙口與水密門" },
  { id: "head-ledge", group: "Cargo", en: "Head ledge", zh: "艙口端樑",
    def: "Those athwartship are called head ledges. The head ledges rest on the beams and the carlings extending between the beams.",
    note: "橫向的兩件。宜與艙口圍板一併記憶，考試常把兩者對調提問。",
    source: "00_術語表_中英定義.md · 艙口與水密門" },
  { id: "hold", group: "Cargo", en: "Hold", zh: "貨艙", cutaway: true,
    def: "The cargo stowage compartments in a ship.",
    note: "裝貨的艙格。雜貨船的特徵是貨艙大而空敞。",
    source: "00_術語表_中英定義.md · 船型與船上設施；00_溫習清單.md · general cargo ship 特徵" },
  { id: "tween-deck", group: "Cargo", en: "Tween deck", zh: "二層甲板", cutaway: true,
    def: "One or more separate decks are fitted in the cargo holds are known as Tween decks for cargo segregation and improved stability. The upper cargo stowage compartments or the space between any two adjacent decks.",
    note: "用以分隔貨物並改善穩性。散裝船不設二層甲板，以便快速裝卸。",
    model: "切開後，淺色層板即為二層甲板，其上、下皆為貨艙。層板繪得稍厚，以便在剖面中辨認。",
    source: "00_術語表_中英定義.md · 船型與船上設施" },
  { id: "bulkhead", group: "Cargo", en: "Bulkhead", zh: "艙壁", cutaway: true,
    def: "Walls are called bulkheads. Bulkheads are vertical partitions going across the ship or fore and aft.",
    note: "垂直隔板。與甲板一同把船分成水密艙格；船舶進水而不沉，有賴於此。",
    source: "00_術語表_中英定義.md · 船體結構" },
  { id: "double-bottom", group: "Cargo", en: "Double bottom", zh: "雙層底", cutaway: true,
    def: "A double bottom is fitted to extend the length of the ship, and is divided into separate tanks.",
    note: "分成獨立艙櫃，部分裝載燃油及淡水，其餘用作壓載。",
    source: "00_術語表_中英定義.md · 船型與船上設施" },
  { id: "fore-peak", group: "Cargo", en: "Fore peak tank", zh: "艏尖艙", cutaway: true,
    def: "Fore and aft peak tanks are fitted to assist in trimming the ship. Aft peak is a watertight compartment between the aftermost watertight bulkhead and the stern.",
    note: "艏尖艙與艉尖艙，用以調整縱傾。",
    source: "00_術語表_中英定義.md · 船型與船上設施" },
  { id: "aft-peak", group: "Cargo", en: "Aft peak tank", zh: "艉尖艙", cutaway: true,
    def: "Fore and aft peak tanks are fitted to assist in trimming the ship. Aft peak is a watertight compartment between the aftermost watertight bulkhead and the stern.",
    note: "艏尖艙與艉尖艙，用以調整縱傾。",
    source: "00_術語表_中英定義.md · 船型與船上設施" },
  { id: "ballast", group: "Cargo", en: "Ballast", zh: "壓載", cutaway: true,
    def: "A weight of liquid positioned in a ship to change the trim, because the draught or improve the seaworthiness.",
    note: "用以調整縱傾，並保證吃水及螺旋槳全浸。",
    model: "點選此項會同時標示雙層底及艏艉尖艙。壓載是艙內的液體，不是某一塊構件。",
    source: "00_術語表_中英定義.md · 船型與船上設施；00_溫習清單.md · general cargo ship 特徵" },
  { id: "engine-room", group: "Cargo", en: "Engine room", zh: "機艙", cutaway: true,
    def: "",
    note: "船尾佈置圖中與艉尖艙、機艙、推進軸一併出現。該頁是一張沒有正文的佈置圖，講義沒有定義句。",
    source: "00_溫習清單.md · 講義冇教／船尾佈置圖" },

  { id: "crane", group: "Gear", en: "Deck crane", zh: "甲板起重機",
    def: "",
    note: "起重機有三個動作（hoisting、luffing、slewing）及部件：jib / boom、hoisting wire、luffing wire、hoisting winch、operator's cabin / controls、tower（rotating part）、fixed foundation。",
    model: "模型繪有 fixed foundation、tower、cabin、jib。鋼絲與絞車的名稱以溫習清單該句為準。",
    source: "06_Cargo_Gear_and_Hatch_Covers/00_溫習清單.md · Crane" },
  { id: "derrick", group: "Gear", en: "Derrick", zh: "吊桿",
    def: "",
    note: "吊桿裝置是船上最古老的吊裝安排之一，主要用於雜貨船；種類很多，教材只示範其中一種，以說明基本原理及船上術語；有些船至今仍用以進行重件吊裝。桅與甲板一側：cross trees、mast head span block、mast head cargo runner lead block、mast / samson post / derrick post、span rope、derrick heel span lead block、derrick heel cargo runner lead block、derrick stool。吊桿與吊頭一側：derrick（boom）、derrick head span block、derrick head cargo block、lower cargo purchase block、ramshorn hook、cargo runner。",
    model: "模型只繪桅或柱、吊桿及吊鉤，用以辨認位置。部件全名以溫習清單為準。",
    source: "06_Cargo_Gear_and_Hatch_Covers/00_溫習清單.md · Derrick" },
  { id: "anchor", group: "Gear", en: "Anchor", zh: "錨",
    def: "",
    note: "總佈置圖的船體編號表（1–12）：stem、forefoot、keel、rudder post、rudder、propeller、propeller boss、stern、anchor、draught marks、load line markings、deck line。這十二項即為船外可見的部分。",
    source: "00_溫習清單.md · General Arrangement Hull 編號表" },
  { id: "hawsepipe", group: "Gear", en: "Hawsepipe", zh: "錨鏈筒",
    def: "",
    note: "（第 19 頁圖上標示）錨鏈穿出船殼的管子。",
    source: "00_術語表_中英定義.md · 船體結構" },
  { id: "propeller", group: "Gear", en: "Propeller", zh: "螺旋槳",
    def: "",
    note: "總佈置圖的船體編號表（1–12）：stem、forefoot、keel、rudder post、rudder、propeller、propeller boss、stern、anchor、draught marks、load line markings、deck line。這十二項即為船外可見的部分。壓載艙用以保證吃水及螺旋槳全浸。",
    source: "00_溫習清單.md · General Arrangement；general cargo ship 特徵" },
  { id: "rudder", group: "Gear", en: "Rudder", zh: "舵",
    def: "",
    note: "總佈置圖的船體編號表（1–12）包括舵。舵柱是位於船尾的垂直結構構件，用以固定舵。",
    source: "00_溫習清單.md · General Arrangement；00_術語表 · Rudder post" },
  { id: "rudder-post", group: "Gear", en: "Rudder post", zh: "舵柱",
    def: "Rudder Post: The vertical structural member at the stern to which the rudder is attached.",
    note: "位於船尾的垂直結構構件，用以固定舵。",
    source: "00_術語表_中英定義.md · 要背 · 船舶主尺度" },

  { id: "waterline", group: "Marks", en: "Waterline", zh: "水線",
    def: "The line where the surface of the water intersects the ship's hull.",
    note: "水面與船體相交的線。",
    source: "00_術語表_中英定義.md · 要背 · 船舶主尺度" },
  { id: "draught", group: "Marks", en: "Draught", zh: "吃水",
    def: "Draught is the distance from the keel to the waterline as measured at the forward and aft ends of the ship. It is expressed in metres.",
    note: "由龍骨量至水線的距離，在船首及船尾量度，以米表示。此數值決定船舶能否進入該港口。船深 = 吃水 + 乾舷。",
    model: "模型中龍骨為 0、水線為 7、船舯主甲板為 10。即模型內吃水為 7、乾舷為 3、船深為 10。單位仍依講義：吃水用米，乾舷用毫米。",
    source: "00_術語表_中英定義.md · 要背 · 吃水、乾舷、浮力" },
  { id: "draught-marks", group: "Marks", en: "Draught marks", zh: "吃水標尺",
    def: "They are usually positioned at the bows, stern and amidships. The marks are one metre apart, and only even numbers are used.",
    note: "相距 1 米，只用雙數。船首 12 米、船尾 13 米時，船首水線觸及「12」的下緣，船尾水線觸及上緣。",
    model: "模型上的數字已放大，以便點選。並非講義中 12 米／13 米的例子。",
    source: "00_術語表_中英定義.md · 方位、報告與通訊用語" },
  { id: "freeboard", group: "Marks", en: "Freeboard", zh: "乾舷",
    def: "Freeboard is the distance between the waterline and the top of the uppermost continuous deck. It is expressed in millimetres and is measured amidships.",
    note: "水線至最上層連續甲板的垂直距離，以毫米表示，在船舯量度。兩個單位、一個量度位置，三者皆為考點。船深 = 吃水 + 乾舷。",
    model: "箭頭置於船舯。模型中水線為 7、甲板為 10，乾舷為 3。講義要求記憶的單位是毫米。",
    source: "00_術語表_中英定義.md · 要背 · 吃水、乾舷、浮力" },
  { id: "load-line", group: "Marks", en: "Load line / Plimsoll mark", zh: "載重線圓盤",
    def: "These marks on the ship's sides of Merchant Ships known as Plimsoll Marks indicate the greatest depth to which the ship may be safely loaded under various conditions in accordance with international regulations.",
    note: "標示各種情況下最深可裝載的限度。標記的排列與尺寸：甲板線長 300 mm、圓盤直徑 450 mm、季節線臂長 230 mm、所有線寬 25 mm。",
    model: "圓盤已放大，以便點選。圖上只繪圓盤及穿過圓盤的線。季節線的完整排法與尺寸以溫習清單為準。",
    source: "00_術語表_中英定義.md · Load line Disc；00_溫習清單.md · 標記排位同尺寸" },
  { id: "deck-line", group: "Marks", en: "Deck line", zh: "甲板線",
    def: "",
    note: "標記的排列與尺寸：甲板線長 300 mm、圓盤直徑 450 mm、季節線臂長 230 mm、所有線寬 25 mm。",
    model: "繪於圓盤上方，已放大以便點選。須記憶的長度是 300 mm。",
    source: "00_溫習清單.md · 標記排位同尺寸" }
];
